config/routes.rb
Rails.application.routes.draw do
devise_for :users
root 'articles#index'
resources :articles do
  resources :likes , only: [:create, :destroy]
end
resources :users ,only:[:show]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :text,:title ,presence: true
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :article, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters ,if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :redirect_to_index, except:[:index,:show]
  def index
    @articles=Article.includes(:user).order('created_at DESC').page(params[:page]).per(5)
    @likes = Like.where(article_id: params[:article_id])
  end

  def new
    @article =Article.new
  end

  def show
    article_set
  end

  def edit
    article_set
  end

  def create
    Article.create(article_params)
    redirect_to action: :index
  end

  def destroy
    article_set
    @article.destroy
    redirect_to action: :index
  end

  def update
    article_set
    @article.update(article_params)
    redirect_to action: :index
  end

  private
  def article_params
    params.require(:article).permit(:text,:title).merge(user_id: current_user.id)
  end

  def article_set
    @article=Article.find(params[:id])
  end

  def redirect_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.create(user_id: current_user.id, article_id: params[:article_id])
    redirect_to "/"
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    like.destroy
    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/articles/_article.html.erb
<div class="row ">
        <div class="col s10 offset-s1">
          <div class="card  white darken-1 card-panel hoverable">
            <div class="card-content ">
              <span class="card-title"><%=article.title%></span>
              <p><%=article.created_at%></p>
              <p class="text"><%=article.text%></p>
            </div>
            <div class="card-action">
              <%=link_to 'show', "/articles/#{article.id}"%>
              <% if user_signed_in? && current_user.id == article.user_id%>
              <%=link_to 'edit', "/articles/#{article.id}/edit" %>
              <%=link_to 'destroy', "/articles/#{article.id}" ,method: :delete ,data: { confirm: 'Are you sure?' }%>
              <% end %>
              <%= render partial: 'likes/like', locals: {article: article,likes: @likes, like: @like }%>
            </div>
          </div>
        </div>
      </div>

app/views/articles/edit.html.erb
<%=form_for @article do |f|%>
<div class="row ">
        <div class="col s10 offset-s1">
          <div class="card darken-1 card-panel hoverable">
            <div class="card-content ">
              <%=f.label :title%>
              <%=f.text_field :title%>
              <%=f.label :text%>
              <%=f.text_area :text ,id:"icon_prefix2" ,class:"materialize-textarea"%>
              <%=f.submit type: "submit" ,class:"btn waves-effect waves-light"%>
            </div>
          </div>
        </div>
      </div>
 <% end %>

app/views/articles/index.html.erb
<% @articles.each do |article|%>
 <%=render partial: "articles/article",locals: {article: article}%>
<% end %>
<div class="card-panel teal lighten-2">
 <%=paginate(@articles) %>
</div>

app/views/articles/new.html.erb
<%=form_for @article do |f|%>
<div class="row ">
        <div class="col s10 offset-s1">
          <div class="card darken-1 card-panel hoverable">
            <div class="card-content ">
              <%=f.label :title%>
              <%=f.text_field :title%>
              <%=f.label :text%>
              <%=f.text_area :text ,id:"icon_prefix2" ,class:"materialize-textarea"%>
              <%=f.submit type: "submit" ,class:"btn waves-effect waves-light"%>
            </div>
          </div>
        </div>
      </div>
 <% end %>

app/views/articles/show.html.erb
<div class="row ">
  <div class=>
    <div class="col s10 offset-s1">
     <div class="card  white darken-1 card-panel hoverable">
      <div class="card-content ">
        <h1><%=@article.title%></h1>
        <p class="text"><%=@article.text%></p>
      </div>
       <div class="card-action">
         <p>by_<%=@article.user.username%></p>
         <span class="right"><%=@article.created_at%></span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLOG</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style type="text/css" href="./style.css"></style>
    <meta charset="utf-8";>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>
  </head>

  <body>
   <nav class="cyan lighten-2">
      <div class="nav-wrapper">
        <span class="brand-logo right">B.l.o.g</span>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%=link_to 'blog',"/" %></li>
        <% if user_signed_in?%>
          <li><%=link_to 'Log-out',destroy_user_session_path, method: :delete%></li>
          <li><%=link_to 'put',"/articles/new" %></li>
        <% else %>
          <li><%=link_to 'Log-in',new_user_session_path%></li>
          <li><%=link_to 'Sign-up',new_user_registration_path%></li>
        <% end %>
        </ul>
      </div>
   </nav>
     <div class="progress">
        <div class="determinate" style="width: 70%"></div>
    </div>
  <script type="text/javascript" src="./app.js"></script>
  <div class="pagebody-main">
    <%= yield %>
  </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
<% if article.like_user(current_user)%>
  <%= button_to article_like_path(likes, article_id: article.id),class:" material-icons ",id: "like-button",method: :delete, remote: true do %>
  mood_bad
<% end %>
<% else %>
  <%= button_to article_likes_path(article_id: article.id), id: "like-button left",method: :post,class:"material-icons" ,remote: true do %>
  mood
  <% end %>
<% end %>
<% end %>
  <span class="waves-effect waves-light">good_count: <%= article.likes_count %></span>